server {
    listen 80;
    listen [::]:80;
    server_name example1.com sub1.example1.com sub2.example1.com example2.com sub1.example2.com sub2.example2.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
